# fly.toml app configuration file generated for wadah-kerja on 2025-07-04T03:01:32+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wadah-kerja'
primary_region = 'sin'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[mounts]
    source="storage_vol"
    destination="/var/www/html/storage"

[env]
  APP_ENV = 'development'
  APP_DEBUG = true
  APP_URL = 'https://wadah-kerja.fly.dev'
  # LOG_CHANNEL = 'stderr'
  # LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  SSR_URL="ssr.process.wadah-kerja.internal:13714"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[processes]
    app = ""
    ssr="php /var/www/html/artisan inertia:start-ssr"
